CREATE TABLE conserto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_entrada VARCHAR(10),
  data_saida VARCHAR(10),
  mecanico_nome VARCHAR(255) NOT NULL,
  mecanico_anos_experiencia INTEGER,
  veiculo_marca VARCHAR(255) NOT NULL,
  veiculo_modelo VARCHAR(255) NOT NULL,
  veiculo_ano VARCHAR(4) NOT NULL
);
